version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 15
  assignees:
  - reggieboyyeah
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: chrono-node
    versions:
    - 2.1.10
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: sass-loader
    versions:
    - 10.0.2
  - dependency-name: prettier
    versions:
    - 2.1.2
